# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
<<<<<<< HEAD
      - image: circleci/node:7.10

=======
      - image: circleci/node:10.13.0-browsers
      #  environment:
      #    CHROME_BIN: /usr/bin/google-chrome
>>>>>>> environments
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

<<<<<<< HEAD
      - run: yarn install
=======
      - run: yarn install --ignore-engines
>>>>>>> environments

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
<<<<<<< HEAD
      - run: yarn test
=======
      - run: yarn test
>>>>>>> environments
